name: CI - Build and Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AKKA_REPO_TOKEN: ${{ secrets.AKKA_REPO_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and test with Maven
        run: mvn -B -V -ntp clean verify
